#!zsh

# make sure to run `poetry shell` to get inside the virtualenv before running this script

set -e

_RZD_COMPLETE=zsh_source rzd > completions/rezide.zsh
_RZD_COMPLETE=fish_source rzd > completions/rezide.fish
_RZD_COMPLETE=bash_source rzd > completions/rezide.bash
