name: Coverage
on: push
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.9'
        architecture: x64
    - run: pip install poetry==1.0.5
    - run: make ci-setup
    - run: make test
    - run: poetry run coverage xml --fail-under=0
    - run: poetry run codecov
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
